### PR TITLE
Update for TB68

### PR DESCRIPTION
**Pull request by alainfrisch**
This is @opto's branch, plus local tweaks from me in preparation of the merge.

### CODE REVIEW

**Comment by opto** [comment]
Hi Alain,

This has been so much work that I would prefer  to see my name/a note somewhere in readme.md or about.xhtml (not only in license, changes and manifest, where most likely nobody looks).

Other than that, it looks fine.

Thanks Klaus

**Comment by alainfrisch** [comment]
@opto, I've added an "Authors" section in the README, with a special mention for your much appreciated work!

**Comment by alainfrisch** [comment]
Cherry-picked directly to master after the squash-merge of #74.

**Comment by opto** [comment]
> 
> 
> @opto, I've added an "Authors" section in the README, with a special mention for your much appreciated work!

Alain, thanks.

One thing to consider for the future: rename those letters that are preset by TB (e.g. S = star email). At least for the new users. I think two or three of the four letters are in use by official TB.

**Pull request closed without merging**
