### PR TITLE
Makes Nostalgy compatible with Thunderbird 68

### LINKED ISSUE #71: Thunderbird 68.0
Unfortunately Nostalgy cannot be used with the latest version of Thunderbird anymore:

grafik

Maybe it's just the version range that needs to be updated?

### PR DESCRIPTION
**Pull request by caugner**
Fixes #71.

Work by @opto.

### CODE REVIEW

**Comment by opto** [comment]
Thanks. I am not sure opto/nostalgy/TB68 is fully identical to opto/nostalgy-xpi. More work to come.
Klaus

**Comment by caugner** [comment]
@opto I would opt for finalising some intermediate working state in order to release a working version of nostalgy to the add-ons site. Can you tell whether there any major issues left that would block such an intermediate version?

**Comment by opto** [comment]
maybe I get the rules working.

just give me time till after the weekend. It is truely tedious work due to the many changes inside TB.

Personally, I think having s,m and the rules would be a good time to upload.

But at least a new rule now also comes up in the listbox table. But Rome was not build in one day - it does not store, so that is broken as well. After the weekend, I will know whether this needs mooooore time or only a little

**Comment by madagit** [comment]
I do use the Basic functions, like m, s, and g.
Is opto/nostalgy/TB68 and/or opto/nostalgy-xpi also valid for TB60.* ?

(I do not use the rules in Nostalgy, for this I use the Quickfilters addon)

**Comment by pierredGitHub** [comment]
I am also EXTREMELY interested in getting a Nostalgy version that works with TB68. I am still on TB 60 because of Nostalgy. I only use s, m, g and c. I do not use any rules either.
I see above there was some work that was going to happen 2 weeks ago, but there has not been any news since. Anything that can be shared re the progress?
I look forward to it.

**Comment by caugner** [comment]
@opto Any chance to get the latest changes committed/pushed into the TB68 branch of your fork?

**Comment by caugner** [comment]
@opto Friendly reminder: Could you please push your latest changes from [your xpi](https://github.com/opto/nostalgy-xpi) to [your fork](https://github.com/opto/nostalgy)?

**Comment by caugner** [comment]
@opto ping

**Comment by pierredGitHub** [comment]
I am also awaiting news. Can the latest change be made available? I need a Nostalgy version that works on TB68 so I can upgrade my TB 60.9.1 to TB 68. TB 60.9 has a bug which really annoys me, and which is fixed in 68. But I cannot work without Nostalgy.
Thanks.

**Comment by caugner** [comment]
@pierredGitHub If you trust @opto, you can download the latest working version [here](https://github.com/opto/nostalgy-xpi/raw/master/nostalgy.xpi) and add it manually to TB 68.

**Comment by george-code** [comment]
I'm completely dependent upon Nostalgy, and so I greatly appreciate the efforts of the people who have jumped in to keep it working in TB 68.

I encourage anyone who uses Nostalgy to contribute to the bounty:

https://www.bountysource.com/issues/79559410-thunderbird-68-0

**Comment by pierredGitHub** [comment]
@caugner I did download Nostalgy from the link you specified and am now running TB68.2.2 (finally) with Nostalgy. So far no issue, but it's only been 2-3 hours, so time will tell. Thank you to everyone involved in these developments.

**Comment by MLopez-Ibanez** [comment]
> @opto Friendly reminder: Could you please push your latest changes from [your xpi](https://github.com/opto/nostalgy-xpi) to [your fork](https://github.com/opto/nostalgy)?

@caugner if @opto does not have time or interest to update his fork, perhaps we could have a fork that tracks the latest xpi and submit pull requests from the one. What do you think?

**Comment by alainfrisch** [comment]
@caugner : can you confirmed this is subsumed by #74?

**Comment by caugner** [comment]
@alainfrisch It does. :)

**Pull request closed without merging**
