### PR TITLE
update to tb68

### PR DESCRIPTION
**Pull request by MLopez-Ibanez**
Merge changes from @opto

Pull requests are welcome in the fork.

### CODE REVIEW

**Comment by opto** [comment]
take care: this version disables the possibility to hover the mouse on a link in an email and see in the status line where the link goes to.
Currently, the nostalgy status line hides the statustext where this is displayed. I haven't yet found a way to solve this.

So some safety in displaying links is lost by using this.

opto/Klaus

**Comment by MLopez-Ibanez** [comment]
The status bar is indeed a mess. I hope someone proposes how to fix it.

The other messy thing is that there's a file that is almost duplicated.

**Comment by opto** [comment]
I am on it. It is not clear whether nostalgy messes with the new html implementation of the statusbar, or whether there is a bug in the new implementation. If I use statusbar as proposed, all looks good, but the TB window partly minimises as soon as one clicks into an email. So that is truely still a mess.

**Comment by MLopez-Ibanez** [comment]
> take care: this version disables the possibility to hover the mouse on a link in an email and see in the status line where the link goes to.
> Currently, the nostalgy status line hides the statustext where this is displayed. I haven't yet found a way to solve this.

Actually, my version replaces document.width (which is obsolete) and this moves the nostalgy status text to the right enough so that the link is show. However, it would be better if nostalgy text was right-aligned in the status bar instead of located at 6/4 from the left side of the status bar.

**Comment by MLopez-Ibanez** [comment]
Hi @opto, not sure what you mean, I haven't substituted eval as far as I
can see.

**Comment by alainfrisch** [comment]
@MLopez-Ibanez : thanks for opening this PR.  Now that @opto opened #74, I think it makes sense to do the review process there.  Are there any commits from this PR that @opto should import on his branch (and thus on #74) before it is being merged?

**Comment by MLopez-Ibanez** [comment]
> Are there any commits from this PR that @opto should import on his branch (and thus on #74) before it is being merged?

Yes. At least the build.sh and the use of an UTF-8 arrow symbol.

**Pull request closed without merging**
